"""
PhysDock Tier A: Diffusion Docking with DiffDock-L.

This module acts as the orchestrator for the DiffDock-L generative AI model. DiffDock
treats molecular docking as a diffusion generative process, learning to translate,
rotate, and alter the torsion angles of a ligand starting from pure noise until it 
reaches a highly probable binding pose inside a rigid protein receptor. 

Instead of reimplementing DiffDock's heavy architecture locally, this script acts as 
a robust bridge to the official DiffDock-L command-line interface (CLI). It performs 
three critical tasks:
1. Translates internal Python data structures into the strict CSV format DiffDock expects.
2. Safely executes the DiffDock subprocess in its isolated environment, capturing errors.
3. Recursively parses the output directory structure to extract the generated 3D poses 
   (SDF files) and their associated confidence scores into a tidy Pandas DataFrame.

By generating multiple poses per ligand (e.g., 16 samples), this module effectively 
creates a fast, computationally cheap "conformational ensemble," serving as a surrogate 
for traditional Molecular Dynamics (MD) sampling.
"""
from __future__ import annotations
import subprocess
from pathlib import Path
from typing import Optional

import pandas as pd

from .utils import ensure_dir, get_logger

log = get_logger("physdock.diffdock")


def write_input_csv(complexes: list[dict], out_csv: Path) -> Path:
    """
    Prepares and writes the input CSV file required by the DiffDock-L CLI.

    DiffDock-L requires a specific CSV schema to run inference: 'complex_name', 
    'protein_path', 'ligand_description' (SMILES), and 'protein_sequence'. This 
    function iterates through a provided list of internal complex dictionaries, 
    maps our internal keys to DiffDock's expected column names, converts it into 
    a Pandas DataFrame, and saves it to disk. 

    Args:
        complexes (list[dict]): A list of dictionaries, where each dict represents a 
                                target-ligand pair containing 'ligand_id', 
                                'receptor_pdb', and 'smiles'.
        out_csv (Path): The destination file path for the generated CSV.

    Returns:
        Path: The absolute path to the generated CSV file.

    Example:
        >>> complexes = [{"ligand_id": "sotorasib", "receptor_pdb": "6OIM.pdb", "smiles": "C"}]
        >>> write_input_csv(complexes, Path("diffdock_input.csv"))
        Path('diffdock_input.csv')
    """
    ensure_dir(out_csv.parent)                                            # Create the parent directory for the CSV file if it does not already exist
    df = pd.DataFrame([{                                                  # Initialize a Pandas DataFrame using a list comprehension over the complexes
        "complex_name": c["ligand_id"],                                   # Map the internal 'ligand_id' to DiffDock's 'complex_name' column
        "protein_path": str(c["receptor_pdb"]),                           # Map the path of the cleaned receptor PDB to 'protein_path'
        "ligand_description": c["smiles"],                                # Map the 1D chemical string (SMILES) to 'ligand_description'
        "protein_sequence": "",                                           # Provide an empty string for 'protein_sequence' as it is unused here
    } for c in complexes])                                                # Iterate through every complex dictionary provided in the input list
    df.to_csv(out_csv, index=False)                                       # Write the populated DataFrame to the specified CSV file path without row indices
    log.info("DiffDock input CSV -> %s (%d complexes)", out_csv, len(df)) # Log the successful creation of the CSV and the number of processed complexes
    return out_csv                                                        # Return the path to the newly created CSV file


def run(cfg, ligand_csv: Path, out_dir: Path) -> None:
    """
    Executes the DiffDock-L CLI process using a system subprocess call.

    This function fetches the DiffDock repository path and command template from 
    the central configuration file (target_config.yaml). It verifies the repository 
    exists (to prevent silent failures), formats the command string with the dynamic 
    input/output paths, and executes it in the shell. It captures stdout and stderr, 
    raising a highly actionable RuntimeError if the AI model fails during execution.

    Args:
        cfg (DictConfig): The loaded configuration object (from target_config.yaml).
        ligand_csv (Path): The path to the input CSV generated by write_input_csv.
        out_dir (Path): The directory where DiffDock should save its generated poses.

    Returns:
        None

    Example:
        >>> run(cfg, Path("input.csv"), Path("results/diffdock_out"))
        # (Executes subprocess, logs progress, returns nothing on success)
    """
    repo = cfg.get("diffdock", "repo_dir")                                # Fetch the DiffDock repository directory path from the configuration object
    if not repo or repo.startswith("${"):                                 # Check if the path is missing or remains an unrendered environment variable
        raise RuntimeError(                                               # Throw a fatal error immediately to stop execution rather than failing silently
            "DiffDock repo_dir not set. Clone DiffDock-L and set "        # Provide an actionable error message explaining what is missing
            "PHYSDOCK_DIFFDOCK_DIR=/path/to/DiffDock (see docs/AWS_RUNBOOK.md).") # Point the user to the exact documentation file for the fix
    out_dir = ensure_dir(out_dir)                                         # Ensure the output directory exists, creating it if necessary
    cmd = cfg.get("diffdock", "inference_cmd").format(                    # Fetch the DiffDock command template and inject the dynamic file paths
        ligand_csv=str(ligand_csv), out=str(out_dir),                     # Substitute the input CSV and output directory placeholders
        protein="", ligand_csv_path=str(ligand_csv))                      # Substitute legacy placeholders to maintain compatibility with older configs
    log.info("DiffDock cmd (cwd=%s):\n  %s", repo, cmd)                   # Log the exact command being run and the working directory for debugging
    proc = subprocess.run(cmd, shell=True, cwd=repo, capture_output=True, text=True) # Execute the command in the shell, capturing outputs as text
    if proc.returncode != 0:                                              # Check if the process exited with an error code (anything other than 0)
        log.error("DiffDock stderr tail:\n%s", proc.stderr[-2000:])       # Log the last 2000 characters of the error stream to diagnose the AI failure
        raise RuntimeError(f"DiffDock exited {proc.returncode}")          # Throw a fatal Python error containing the specific bash exit code
    log.info("DiffDock finished -> %s", out_dir)                          # Log a success message indicating the outputs are ready in the directory


def parse_results(out_dir: Path) -> pd.DataFrame:
    """
    Parses the nested directory structure outputted by DiffDock into a tidy DataFrame.

    DiffDock outputs a separate subfolder for each complex. Inside, it places multiple 
    SDF files (poses) named with their rank and confidence score (e.g., 
    'rank1_confidence-0.42.sdf'). This function recursively walks the directory tree, 
    identifies all valid SDF files, extracts the metadata using a helper function, 
    and collates everything into a structured Pandas DataFrame for downstream evaluation.

    Args:
        out_dir (Path): The root directory containing the DiffDock outputs.

    Returns:
        pd.DataFrame: A tidy DataFrame with columns ['ligand_id', 'rank', 
                      'confidence', 'pose_sdf'].

    Example:
        >>> parse_results(Path("results/diffdock_out"))
        # Returns a DataFrame with rows like:
        # ligand_id | rank | confidence | pose_sdf
        # sotorasib | 1    | -0.42      | /path/to/rank1_confidence-0.42.sdf
    """
    rows = []                                                             # Initialize an empty list to store the extracted data dictionaries
    for comp_dir in sorted(Path(out_dir).glob("*")):                      # Iterate over all items in the output directory, sorted alphabetically
        if not comp_dir.is_dir():                                         # Check if the current item is a directory (ignoring loose files)
            continue                                                      # Skip to the next iteration if the item is not a directory
        for sdf in sorted(comp_dir.glob("rank*.sdf")):                    # Iterate over all SDF files starting with 'rank' inside the complex directory
            name = sdf.stem                                               # Extract the filename without the '.sdf' extension (e.g., rank1_confidence-0.42)
            rank, conf = _parse_rank_name(name)                           # Call the helper function to extract the integer rank and float confidence
            rows.append({                                                 # Append a new dictionary representing this pose to the rows list
                "ligand_id": comp_dir.name, "rank": rank,                 # Store the complex folder name as 'ligand_id' and the parsed 'rank'
                "confidence": conf, "pose_sdf": str(sdf),                 # Store the parsed 'confidence' score and the absolute path to the SDF file
            })                                                            # Close the dictionary declaration
    df = pd.DataFrame(rows)                                               # Convert the populated list of dictionaries into a Pandas DataFrame
    if df.empty:                                                          # Check if the DataFrame has zero rows (no poses were found)
        log.warning("No DiffDock poses parsed under %s", out_dir)         # Log a warning alerting the user that the directory was unexpectedly empty
    else:                                                                 # Execute this block if poses were successfully found and parsed
        log.info("Parsed %d DiffDock poses across %d ligands",            # Log the total number of poses found and the unique number of ligands processed
                 len(df), df.ligand_id.nunique())                         # Pass the DataFrame length and unique ligand count to the logger
    return df                                                             # Return the final populated Pandas DataFrame


def _parse_rank_name(name: str) -> tuple[int, Optional[float]]:
    """
    Helper function to parse the rank integer and confidence float from a DiffDock filename.

    Because DiffDock versions sometimes change filename formats slightly (e.g., adding 
    hyphens or underscores), this parser safely splits the string by underscores and 
    extracts the numeric values defensively.

    Args:
        name (str): The filename string without the extension (e.g., "rank1_confidence-0.42").

    Returns:
        tuple[int, Optional[float]]: A tuple containing the parsed rank (defaults to 999 
                                     if missing) and confidence score (defaults to None).

    Example:
        >>> _parse_rank_name("rank1_confidence-0.42")
        (1, -0.42)
    """
    rank, conf = 999, None                                                # Initialize default fallback values: 999 for rank, None for confidence
    for tok in name.split("_"):                                           # Split the filename string by underscores and iterate through the tokens
        if tok.startswith("rank"):                                        # Check if the current token begins with the word 'rank'
            digits = "".join(ch for ch in tok if ch.isdigit())            # Extract all numeric characters from the token into a single string
            rank = int(digits) if digits else rank                        # Convert the extracted digits to an integer, or keep the default if empty
        if "confidence" in tok:                                           # Check if the current token contains the word 'confidence'
            try:                                                          # Begin a try block to catch potential string-to-float conversion errors
                conf = float(tok.split("confidence")[-1].lstrip("-_"))    # Split by 'confidence', take the right side, strip hyphens/underscores, and cast to float
                if "confidence-" in name:                                 # Check if the original filename explicitly had a minus sign after confidence
                    conf = -abs(conf)                                     # Force the parsed float to be negative to preserve the original sign
            except ValueError:                                            # Catch the error if the string could not be converted into a valid float
                conf = None                                               # Revert the confidence variable to None if parsing failed
    return rank, conf                                                     # Return the extracted integer rank and float confidence tuple