#!/usr/bin/env python
"""
=============================================================================
PhysDock: Stage 02 — The Cheminformatics Gate
=============================================================================
This script acts as the automated "bouncer" for the PhysDock pipeline. 
Deep Learning structural models (like DiffDock-L and Boltz-2) are incredibly 
computationally expensive (requiring GPU time) and operate purely on spatial 
geometry. If you feed them a mathematically impossible molecule, they will 
waste hours attempting to dock it.

This CPU-bound script solves that problem. It loads the parsed SMILES strings 
from Stage 01 and subjects them to rigorous cheminformatics quality control. 
It filters out:
  1. Chemically invalid structures (bad valency).
  2. Implausible physical properties (too massive, too lipophilic).
  3. Synthetically inaccessible molecules (impossible to make in a lab).
  4. PAINS (Pan-Assay Interference Compounds - known false-positive troublemakers).

It generates a master CSV ledger (`results/chem/chem_gate.csv`), flagging and 
down-ranking impossible drugs BEFORE the pipeline spends a single GPU dollar on them.
"""
import argparse
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))                     # Dynamically inject the parent directory into the Python path to allow local module imports.
from physdock import chem                                                        # Import the core cheminformatics module which contains the evaluation logic (MW, LogP, PAINS).
from physdock.config import load_config                                          # Import the configuration loader to access project-specific threshold settings.
from physdock.utils import get_logger, load_json, ensure_dir                     # Import utility functions for standardized logging, JSON parsing, and directory management.

log = get_logger("02_chem_gate")                                                 # Initialize a module-level logger named "02_chem_gate" to track the execution status.


def main(cfg_path):
    # Load Configuration YAML and Pre-processed Data (target_prep.json).
    cfg = load_config(cfg_path)                                                  # Parse the specified YAML configuration file into a manageable Config object.
    prep = load_json("data/processed/target_prep.json")                          # Load the pre-processed target data generated by Stage 01, which contains the extracted SMILES.
    # Evaluate Each Ligand's Chemistry (MW, LogP, PAINS, SA, etc.) and Compile Results.
    rows = []                                                                    # Initialize an empty list to accumulate the chemistry evaluation results for each ligand.
    for lid, info in prep["ligands"].items():                                    # Iterate over every prepared ligand, unpacking its ID and its metadata dictionary.
        smi = info.get("smiles")                                                 # Extract the 1D SMILES string representation of the drug from the metadata dictionary.
        if not smi:                                                              # Check if the SMILES string is missing (e.g., if Stage 01 failed to extract it from the PDB).
            log.warning("%s has no SMILES (ligand extraction failed); skipping.", lid) # Log a warning that this specific ligand cannot be evaluated and must be dropped.
            continue                                                             # Skip the rest of the loop for this corrupted ligand and proceed to the next one.
        rows.append(chem.evaluate_ligand(lid, smi).to_row())                     # Evaluate the ligand's chemistry, convert the resulting dataclass to a dictionary, and append it.
    # Save the Chemistry Evaluation Results (accumulated list of dictionary results)
    # to CSV and Print a Summary Table.
    df = pd.DataFrame(rows)                                                      # Convert the accumulated list of dictionary results into a structured Pandas DataFrame.
    out = ensure_dir("results/chem") / "chem_gate.csv"                           # Ensure the 'results/chem' output directory exists and construct the final output filepath.
    df.to_csv(out, index=False)                                                  # Write the evaluation DataFrame to disk as a CSV file, omitting the arbitrary row indices.
    log.info("Chem gate -> %s", out)                                             # Log a confirmation message showing exactly where the evaluation results were saved.
    if not df.empty:                                                             # Check if the DataFrame actually contains data before attempting to print a summary table.
        log.info("\n%s", df[["ligand_id", "mw", "logp", "sa_score",              # Select key molecular columns and log them as a neatly formatted, index-free string table...
                              "pains_alerts", "passes", "reason"]].to_string(index=False)) # ...providing an immediate, human-readable overview of the filter results in the terminal.

# Execute the main function if this script is run directly (not imported as a module),
# passing the command-line argument for the configuration file path, which defaults to "configs/kras_g12c.yaml" if not specified by the user.
if __name__ == "__main__":
    ap = argparse.ArgumentParser()                                               # Initialize the standard argument parser to handle command-line inputs.
    ap.add_argument("--config", default="configs/kras_g12c.yaml")                # Define the '--config' argument, defaulting to the KRAS G12C target configuration if omitted.
    main(ap.parse_args().config)                                                 # Parse the command-line arguments and trigger the main execution function with the specified config path.