#!/usr/bin/env python
"""
=============================================================================
PhysDock: Stage 03 — Tier A Diffusion Docking Orchestrator (DiffDock-L)
=============================================================================
This script serves as the primary execution engine for the Tier A generative 
AI model, DiffDock-L. It acts as the critical bridge between the prepared 
cheminformatics data (Stage 01/02) and the heavy GPU-bound diffusion model.

DiffDock treats molecular docking as a diffusion generative process, sampling 
multiple probable binding poses (a conformational ensemble) for each ligand 
inside a rigid protein receptor. 

The script performs three orchestrated operations:
1. Data Marshalling: Translates the internal `target_prep.json` pipeline state 
   into the strict CSV format required by the external DiffDock CLI.
2. Subprocess Execution: Triggers the GPU-accelerated DiffDock inference engine.
3. Output Harmonization: Parses the deeply nested, complex output directories 
   generated by the AI, extracting the 3D SDF poses and their respective 
   confidence scores, and flattens them into a single, highly queryable 
   CSV file (`poses.csv`) for downstream physics evaluation.
   
It also features a strict MLOps `--skip-run` flag, allowing scientists to 
re-parse massive output datasets without re-triggering expensive GPU compute.
"""
import pathlib
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))                             # Dynamically inject the parent root directory into Python's path for local module resolution
from physdock import docking_diffdock as dd                                              # Import the DiffDock orchestration module containing the CLI wrappers and parsers
from physdock import chem                                                                # Import the chem module to consult the Stage-02 gate (drop chemically invalid ligands)
from physdock.config import load_config                                                  # Import the configuration loader to access YAML parameters
from physdock.utils import get_logger, load_json, ensure_dir, set_seed                   # Import internal pipeline utilities for state management, logging, and reproducibility

log = get_logger("03_diffdock")                                                          # Initialize the module-level logger under the identifier '03_diffdock'


def main(cfg_path, skip_run):
    # Set seed for reproducibility, load the master configuration, and check if 
    # DiffDock execution is enabled in the YAML config. If not enabled, log the skip and exit early.
    set_seed()                                                                           # Lock the random number generators to ensure reproducibility of the pipeline run
    cfg = load_config(cfg_path)                                                          # Load and parse the master target configuration YAML file
    if not cfg.get("diffdock", "enabled", default=True):                                 # Check the configuration boolean flag to see if DiffDock Tier A execution is requested
        log.info("DiffDock disabled in config; skipping."); return                       # Log the skip action and exit the function early if DiffDock is turned off
    # Load the prepared target state, ensure the output directory exists, and 
    # marshal specific dictionary data into DiffDock's required input format (CSV).
    prep = load_json("data/processed/target_prep.json")                                  # Load the prepared ground-truth receptor and ligand state generated by Stage 01
    out_dir = ensure_dir("results/diffdock").resolve()                                   # Ensure the DiffDock results directory exists on the filesystem, creating it if needed; absolute path resolution is applied for portability.
    # Extract the list of ligands that passed Stage-02 chem gate, filter the prepared ligands
    # to only those with valid SMILES, and marshal them into the DiffDock-required CSV format.
    passing = chem.passing_ligand_ids()                                                  # Read the Stage-02 chem-gate ledger (None => gate not run, so don't filter)
    if passing is not None:                                                              # Only filter when the gate has actually produced a ledger
        log.info("Chem gate: %d ligand(s) cleared for docking", len(passing))            # Report how many ligands the gate cleared for the GPU stage
    complexes = [{"ligand_id": lid, "receptor_pdb": str(pathlib.Path(info["receptor_pdb"]).resolve()),                # Initialize a list comprehension to build the specific data dictionaries DiffDock requires
                  "smiles": info["smiles"]}                                              # Map the ligand's 1D SMILES string to the rigid 3D receptor PDB file path
                 for lid, info in prep["ligands"].items()                                # Iterate through all prepared ligands...
                 if info.get("smiles") and (passing is None or lid in passing)]          # ...keeping only those with SMILES that also cleared the chem gate (if it ran)
    csv = dd.write_input_csv(complexes, out_dir / "diffdock_input.csv")                  # Transform the Python dictionaries into the mandatory input CSV file expected by the DiffDock CLI
    # Conditionally execute the DiffDock CLI subprocess based on the MLOps (skip-run) flag, 
    # parse the output directory to extract the 3D poses and confidence scores, and save the harmonized results to a single CSV file. 
    if not skip_run:                                                                     # Evaluate the MLOps flag to determine if actual GPU execution should occur
        dd.run(cfg, csv, out_dir / "raw_out")                                            # Execute the heavy GPU-bound DiffDock CLI subprocess, saving raw hierarchical data to 'raw_out'
    poses = dd.parse_results(out_dir / "raw_out")                                        # Recursively traverse the 'raw_out' directory to scrape the generated SDFs and confidence scores
    poses.to_csv(out_dir / "poses.csv", index=False)                                     # Flatten the scraped poses into a single Pandas DataFrame and save it cleanly to disk
    log.info("DiffDock poses -> %s", out_dir / "poses.csv")                              # Log the final successful output path to the user console

# --skip-run is a critical MLOps feature that allows users to bypass the expensive GPU compute step and directly re-parse existing raw outputs. 
if __name__ == "__main__":
    ap = argparse.ArgumentParser()                                                       # Initialize the command-line argument parser for terminal execution
    ap.add_argument("--config", default="configs/kras_g12c.yaml")                        # Define the path argument for the target's YAML configuration, defaulting to KRAS
    ap.add_argument("--skip-run", action="store_true",                                   # Define a boolean flag to skip GPU compute and only run the post-processing parser
                    help="only (re)parse existing raw_out (no GPU)")                     # Provide terminal help text explaining the skip-run functionality
    a = ap.parse_args()                                                                  # Parse the provided command-line arguments into the 'a' namespace object
    main(a.config, a.skip_run)                                                           # Trigger the main orchestrator function with the parsed configuration path and skip flag