#!/usr/bin/env python
"""
=============================================================================
PhysDock: Stage 04 — Tier B Co-Folding & Affinity Prediction (Boltz-2)
=============================================================================
This script orchestrates the heaviest and most advanced AI stage of the pipeline. 
It utilizes Boltz-2, an AlphaFold3-class generative diffusion model, to perform 
joint protein-ligand co-folding. 

Unlike DiffDock (which treats the protein as a rigid statue), Boltz-2 predicts 
the "induced fit" structure—how the protein dynamically wraps around the drug. 
Crucially, it also features an auxiliary neural network head that regresses a 
thermodynamic binding affinity score directly from the generated 3D complex.

Because this is a highly GPU-intensive process, this script is engineered with 
strict MLOps budget constraints (e.g., `--max-ligands`) to prevent cost overruns 
on AWS instances. It dynamically generates required YAML configurations per 
ligand, executes the inference engine, and aggregates the structural confidence 
and affinity predictions into a centralized CSV for downstream evaluation.
"""
import argparse
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))                             # Dynamically add the parent directory to the Python path to allow local package imports
from physdock import cofold_boltz as bz                                                  # Import the custom Boltz-2 wrapper module, aliased as 'bz' for brevity
from physdock import chem                                                                # Import the chem module to consult the Stage-02 gate (drop chemically invalid ligands)
from physdock.config import load_config                                                  # Import the configuration loader to parse the YAML settings
from physdock.utils import get_logger, load_json, ensure_dir, set_seed                   # Import utilities for logging, JSON parsing, directory management, and deterministic randomness

log = get_logger("04_boltz")                                                             # Initialize the module-level logger tagged "04_boltz"


def main(cfg_path, max_ligands):
    # Set the seed for reproducibility, load the configuration YAML, check if 
    # Boltz is enabled in the config file, and exit early if it's not.
    set_seed()                                                                           # Lock the random number generators (numpy, random, torch) to ensure reproducible runs
    cfg = load_config(cfg_path)                                                          # Load and parse the master project configuration file
    if not cfg.get("boltz", "enabled", default=True):                                    # Check the configuration to see if the user explicitly turned off this expensive stage
        log.info("Boltz disabled in config; skipping."); return                          # Log the skip action and exit the function immediately if Boltz is disabled
    # Load the pre-processed target data .json, extract the amino acid sequence of the 
    # target protein, set up the output directory, and read the predict_affinity flag from the config.
    prep = load_json("data/processed/target_prep.json")                                  # Load the pre-processed target data generated by Stage 01
    seq = prep.get("protein_sequence")                                                   # Extract the raw amino acid sequence of the target protein
    if not seq:                                                                          # Defensive check: Ensure the sequence was actually found and parsed
        log.error("No protein sequence in target_prep.json; run stage 01 first."); return # Log a fatal error and exit if the sequence is missing, directing the user to the prerequisite stage
    out_dir = ensure_dir("results/boltz")                                                # Ensure the destination directory for Boltz outputs exists, creating it if necessary
    pa = cfg.get("boltz", "predict_affinity", default=True)                              # Retrieve the boolean flag dictating whether Boltz should calculate binding affinity

    # Extract a list of (ligand_id, data) tuples, keeping only those with valid SMILES 
    # strings that passed the Stage-02 chem gate, and apply the optional max_ligands cap.
    passing = chem.passing_ligand_ids()                                                  # Read the Stage-02 chem-gate ledger (None => gate not run, so don't filter)
    if passing is not None:                                                              # Only filter when the gate has actually produced a ledger
        log.info("Chem gate: %d ligand(s) cleared for co-folding", len(passing))         # Report how many ligands the gate cleared for this GPU stage
    items = [(lid, info) for lid, info in prep["ligands"].items()                        # Build the (ligand_id, data) work list...
             if info.get("smiles") and (passing is None or lid in passing)]              # ...keeping only ligands with SMILES that also cleared the chem gate (if it ran)
    if max_ligands:                                                                      # Check if the user passed a command-line argument to limit the number of runs (budget cap)
        items = items[:max_ligands]                                                      # Slice the list to keep only the first 'max_ligands' elements
        log.info("Budget cap: running Boltz on first %d ligands", max_ligands)           # Log a warning that the run is being truncated to protect the AWS budget

    # Iterate sequentially over the filtered list of ligands, generate appropriate input 
    # YAMLs for Boltz CLI, and run Boltz for each ligand.
    frames = []                                                                          # Initialize an empty list to accumulate pandas DataFrames containing the results
    for lid, info in items:                                                              # Iterate sequentially over every approved ligand in the filtered list
        yml = bz.write_input_yaml(lid, seq, info["smiles"],                              # Call the wrapper to generate the specific input YAML file required by the Boltz CLI
                                  out_dir / "inputs" / f"{lid}.yaml", pa)                # Pass the destination path for this YAML and the predict_affinity boolean flag
        try:                                                                             # Open a try-block to catch isolated failures (preventing one bad drug from crashing the whole batch)
            bz.run(cfg, yml, out_dir / "preds" / lid)                                    # Execute the heavy Boltz inference engine for this specific ligand
        except Exception as e:  # noqa: BLE001                                           # Catch any inference exceptions (e.g., CUDA OutOfMemory or invalid chemistry)
            log.error("Boltz failed for %s: %s", lid, e); continue                       # Log the exact failure and immediately continue to the next drug in the loop
        frames.append(bz.parse_results(out_dir / "preds" / lid))                         # If successful, parse the generated JSON output files into a DataFrame and append it to the list
    # Parse all the generated .json (Boltz output) results into a master DataFrame
    df = pd.concat([f for f in frames if not f.empty], ignore_index=True) if frames else pd.DataFrame() # Concatenate all individual ligand DataFrames into one master DataFrame, or create an empty one if all failed
    # Collapse the per-diffusion-sample rows to one best row per ligand (highest confidence_score 
    # sample first, highest ipTM second). This prevents a 1-to-many merge blow-up in stage 07.
    df = bz.reduce_best_per_ligand(df)                                                   
    # Also apply the boltz_min_iptm confidence gate (drops low-interface-confidence complexes; never empties the table)
    df = bz.apply_iptm_gate(df, cfg)                                                     
    df.to_csv(out_dir / "boltz.csv", index=False)                                        # Write the master DataFrame to disk as a CSV file, dropping the pandas index column
    log.info("Boltz results -> %s (%d rows)", out_dir / "boltz.csv", len(df))            # Log the successful completion of the stage and the total number of processed predictions


if __name__ == "__main__":
    ap = argparse.ArgumentParser()                                                       # Initialize the command-line argument parser
    ap.add_argument("--config", default="configs/kras_g12c.yaml")                        # Define the path to the main configuration file
    # Define an optional command-line argument to cap the number of ligands to run 
    # through Boltz. The default is None (no cap).
    ap.add_argument("--max-ligands", type=int, default=None,                             # Define the optional budget-saving argument to cap the number of runs
                    help="cap ligand count to protect GPU budget")                       # Provide a help string explaining the purpose of the max-ligands flag
    a = ap.parse_args()                                                                  # Parse the arguments provided by the user in the terminal
    main(a.config, a.max_ligands)                                                        # Execute the main orchestrator function with the parsed arguments