#!/usr/bin/env python
"""
=============================================================================
PhysDock: Stage 05 — Physics Integration & Pose Rescoring
=============================================================================
This script executes the critical thermodynamic "reality check" on the structural 
predictions generated by Tier A (DiffDock-L). 

While generative models are excellent at rapidly sampling conformational landscapes, 
they lack an inherent understanding of physical laws (e.g., Pauli exclusion principle, 
bond strain). This script acts as the orchestrator for the `physics_openmm.py` module.
It ingests the AI-generated ligand poses from Stage 03 (DiffDock-L), filters them to 
limit the GPU-demanding compute costs, and subjects them to either a lightweight MMFF 
strain proxy or a rigorous OpenMM thermodynamic relaxation (Amber14/GAFF2 force fields).

By preserving the AI's original ranking alongside the new physics scores (pose drift, 
interaction energy), this stage generates the necessary data to evaluate whether 
incorporating explicit physics improves the prioritization of drug candidates.
"""
import argparse
import sys
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))                             # Dynamically insert the parent directory into Python's path for local package resolution
from physdock import physics_openmm as phys                                              # Import the core physics engine logic, aliased as 'phys'
from physdock import ensemble                                                            # Import the ensemble module to apply the DiffDock confidence gate BEFORE expensive physics
from physdock.config import load_config                                                  # Import the configuration loader to read the requested physics mode
from physdock.utils import get_logger, load_json, ensure_dir                             # Import standard utility functions for logging and file management

log = get_logger("05_physics")                                                           # Initialize the module-level logger tagged "05_physics"


def main(cfg_path, top_per_ligand):
    # Load configuration, pre-processed protein target data, and DiffDock poses CSV.
    cfg = load_config(cfg_path)                                                          # Load and parse the project configuration YAML to determine the physics mode (e.g., OpenMM)
    prep = load_json("data/processed/target_prep.json")                                  # Load the pre-processed target data dictionary to locate the rigid receptor files
    poses_csv = Path("results/diffdock/poses.csv")                                       # Define the exact filesystem path where DiffDock's generated poses are expected to reside
    if not poses_csv.exists():                                                           # Defensively check if the DiffDock output file actually exists on the disk
        log.error("No DiffDock poses; run stage 03 first."); return                      # Log a fatal error and exit the pipeline immediately if DiffDock hasn't been run yet
    poses = pd.read_csv(poses_csv)                                                       # Read the CSV containing the paths and AI-confidence ranks of all generated poses
    # Confidence gate is applied first: dropping low-probability DiffDock poses before 
    # spending any physics compute on them ("gate before the expensive physics step" guarantee).
    poses = ensemble.apply_confidence_gate(poses, cfg)                                   # Discard poses below ensemble.confidence_gate.diffdock_min_confidence
    # Keep best `top_per_ligand` poses per ligand to limit physics cost
    poses = (poses.sort_values(["ligand_id", "rank"])                                    # Sort the dataframe first by ligand name, then by the AI's internal confidence rank
             .groupby("ligand_id").head(top_per_ligand))                                 # Group by ligand and strictly slice off only the top N poses to save expensive GPU compute time
    # Iterate through the kept poses, run physics scoring, and accumulate results.
    rows = []                                                                            # Initialize an empty list to accumulate the physics scoring results for each pose
    for _, r in poses.iterrows():                                                        # Iterate sequentially through the dynamically filtered dataframe of poses
        # Find the specific receptor PDB file path for this ligand from the pre-processed data.
        rec = prep["ligands"].get(r["ligand_id"], {}).get("receptor_pdb")                # Look up the specific, structurally-cleaned receptor PDB file path for this specific ligand
        if not rec:                                                                      # Check if the receptor path lookup failed (e.g., the ligand failed stage 01 preparation)
            continue                                                                     # Silently skip this corrupted ligand and continue the loop with the next row
        # Execute physics scoring (OpenMM or proxy) on the pose and accumulate results
        # to a list of dictionaries, retaining the original AI rank for later analysis.
        res = phys.score(r["ligand_id"], r["pose_sdf"], rec, cfg)                        # Execute the core physics module (OpenMM or lightweight proxy) on the generated 3D pose
        d = res.to_row(); d["rank"] = r["rank"]; rows.append(d)                          # Convert the result to a dict, inject the original AI rank for traceability, and append to the list
    # After processing all poses, convert the accumulated physics results into a 
    # DataFrame and write to a CSV.
    df = pd.DataFrame(rows)                                                              # Convert the accumulated list of physics dictionaries back into a standard pandas DataFrame
    out = ensure_dir("results/physics") / "physics.csv"                                  # Ensure the output directory exists and construct the final target path for the CSV
    df.to_csv(out, index=False)                                                          # Write the aggregated physics scores to disk, omitting the pandas integer index column
    log.info("Physics (mode=%s) -> %s (%d poses)",                                       # Log a comprehensive success message detailing the run parameters
             cfg.get("physics", "mode", default="lightweight"), out, len(df))            # Print the specific physics mode utilized, the output path, and the total processed pose count


if __name__ == "__main__":
    ap = argparse.ArgumentParser()                                                       # Initialize the standard command-line argument parser
    ap.add_argument("--config", default="configs/kras_g12c.yaml")                        # Define the required path argument pointing to the master configuration file
    ap.add_argument("--top-per-ligand", type=int, default=3)                             # Define the budget-saving argument limiting how many poses per ligand get simulated
    a = ap.parse_args()                                                                  # Parse the arguments passed via the shell/terminal
    main(a.config, a.top_per_ligand)                                                     # Trigger the orchestrator function with the validated arguments